//FORMSCHEME
export const LOAD_FORM_SCHEME = "LOAD_FORM_SCHEME";
export const ADD_FORM_SCHEME = "ADD_FORM_SCHEME";
export const FORM_SCHEME_ERROR = "FORM_SCHEME_ERROR";
export const SET_HEADLINE = "SET_HEADLINE";
export const COMPLETE_STEP = "COMPLETE_STEP";
export const ADD_INITIAL_STEPS = "ADD_INITIAL_STEPS";
